config/routes.rb
Rails.application.routes.draw do
  root 'products#search'

  resources :products, only: [] do
    collection do
      get 'search(/:asin)', action: :search, as: :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  # asin: string
  # category: string
  # dimensions: string
  has_many :product_rankings, dependent: :destroy

  validates :asin, presence:true, uniqueness: true
  validates :category, presence:true
end

app/models/product_ranking.rb
class ProductRanking < ApplicationRecord
  # number: integer
  # category: string
  belongs_to :product

  validates :number, numericality: true
  validates :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def search
    return unless params[:asin].present?
    @product = ProductScraper.new(params[:asin]).retrieve_product
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmazonAsinScraper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/search.html.slim
h1 Search
= form_tag search_products_path, method: :get do
  = text_field_tag :asin, params[:asin], placeholder: 'ASIN'
  = submit_tag 'Search'
br
- if @product.present?
  #result
    p
      b ASIN:
      br
      = @product.asin

    p
      b Category:
      br
      = @product.category

    p
      b Product Dimensions:
      br
      = @product.dimensions

    p
      b Best Sellers Rank:
      br
      - @product.product_rankings.each do |ranking|
        = "##{ranking.number} in #{ranking.category}"
        br

- elsif params[:asin]
  h3 Product Not Found